databases:
  - name: taskpet
    plan: free
    databaseName: taskpet
    user: taskpet

services:
  - type: web
    name: taskpet
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taskpet
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
